name: "Hello Actions"
descrption: "Greet someone"
author: "weimeng"

inputs:
  MY_NAME:
    descrption: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"
  
 branding:
  icon: "mic"
  color: "purple"
